### ISSUE TITLE
More log level ?

### ISSUE THREAD

**Issue by Socolin** [poucotm/Log-Highlight#4]
Hi,

This plugin seems great but I can't find how to add other level to color notice/debug/alert/emergency logs (whose are unix syslog levels)
Is there any way to do this ?

Maybe it could be nice to have a map to define levels instead of error_enable and error_pattern... and be able to define color at the same location

```
{
  "error": {
    "enable": true,
    "pattern": [ ... ],
    "color" : {
        "base": "#FF0000"
        "link": "#FF0000"
        "quote": "#0000FF"
     },
    "quote_pattern": ["[^\\"]+"], ["'[^']+'"] ["`.*'"]
  }
}
```

**Comment by poucotm** [comment]
Hi,

That's great idea to extend log level and it is more systematic. Currently
log level is limited as error, warning, info. Because I didn't need many
levels. If I change the codes and settings, other people also have to
change their customized settings. I will refer to your good idea next time.

Thank you.

Best Regards,
Kris

2017. 3. 14. 오전 8:17에 "Socolin" <notifications@github.com>님이 작성:

**Comment by giaplv57** [comment]
Well we can make additional log levels as optional setting, right?
Say the error, warning, info levels are default, not require user to re-config; and user have the power to define a new log level via user setting.
Thanks,
Giap

**Comment by poucotm** [comment]
Hi, Socolin

I've changed `log highlight` as you said. Just check version v1.0.0.
Thank you for interest.

Best Regards,
Kris


2017-03-14 8:17 GMT+09:00 Socolin <notifications@github.com>:
