### ISSUE TITLE
Create project config option to specify base path

### ISSUE THREAD

**Issue by robrecord** [poucotm/Log-Highlight#8]
Due to the set up of my development environment, I can't change the PHP error log to be in the same directory as my base path.

Can you please allow for manual setting of a base path in the sublime project settings, so that my links can work?

**Comment by poucotm** [comment]
Hi, you can use "set as base" command in the context menu in sidebar. Or do
you need something different way ?


2017. 10. 21. 오전 12:30에 "Rob Record" <notifications@github.com>님이 작성:

Due to the set up of my development environment, I can't change the PHP
error log to be in the same directory as my base path.

Can you please allow for manual setting of a base path in the sublime
project settings, so that my links can work?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/poucotm/Log-Highlight/issues/8>, or mute the thread

**Comment by robrecord** [comment]
Thanks, I didn't know this was a possibility.

Where does it save it to? Can I allow it to save this base path to my .sublime-project file?

**Comment by poucotm** [comment]
Hi,
The package has been updated (v1.8.3). Originally, when you select 'Log Highlight - Set as base ...' in the context menu, the path will be stored in the view settings. Now, it also will be stored in the .sublime-project file if a project file exists. When the package searches base, it will be the first candidate path.

**Comment by robrecord** [comment]
Thank you, I really appreciate that you added this. It will make my workflow much easier when working on different machines or across multiple developers.

**Comment by poucotm** [comment]
Hmm, the stored path is absolute. I don't think it can be used across machnes ... You may need the relative path from the top project folder, don't you?

**Comment by robrecord** [comment]
Yes I would need the relative path from the top project folder - is that possible to achieve?

Otherwise I will have to keep changing the path when I switch, or keep two different .sublime-project files.

**Comment by poucotm** [comment]
It may be possible to store relative path in project file and combine with project path. But I have to try in detail.

**Comment by pouco26** [comment]
I've changed to store the relative instead of absolute path. Would you try ?

**Comment by poucotm** [comment]
I've changed to store the relative instead of absolute path. Would you try ?

**Comment by robrecord** [comment]
Thank you poucotm for doing this, I will try it today.
